name: Build

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run dist
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/*.AppImage

  build-windows:
    runs-on: windows-latest
    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.electron-cache
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.electron-builder-cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.electron-cache
            ${{ github.workspace }}/.electron-builder-cache
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-
      - run: npm install
      - run: npm run dist
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/*.exe
